import MemberCard from '@/components/organisms/MemberCard.vue'

export default {
  name: 'SubSection7',
  components: { MemberCard },
  data: () => ({
    imgSrc1: require('@/assets/oupc/img/leader.jpg'),
    imgSrc2: require('@/assets/oupc/img/cheer.jpg'),
    imgSrc3: require('@/assets/oupc/img/suisou.jpg'),
    members1: [
      {
        name: '戸田　吉久',
        txtBody: '',
        job: '団長・広報',
        position: '幹部',
        school: '大阪府私立開明',
        course: '外国語学部ドイツ語専攻',
        imgSrc: require('@/assets/oupc/img/member/person10.JPG'),
      },

      {
        name: '能登　樹',
        txtBody: '',
        job: 'リーダー部長・渉外',
        position: '幹部',
        school: '岡山県立倉敷青陵',
        course: '工学部応用自然科学科',
        imgSrc: require('@/assets/oupc/img/member/person12.JPG'),
      },
      {
        name: '樋口　泰蔵',
        txtBody: '',
        job: '',
        position: '準幹部',
        school: '愛知県立明和',
        course: '文学部人文地理学専修',
        imgSrc: require('@/assets/oupc/img/member/person2.png'),
      },
    ],
    members2: [
      {
        name: '中村　日南',
        txtBody: '',
        job: '副団長・主務',
        position: '幹部',
        school: '大分県立大分上野丘',
        course: '外国語学部インドネシア語専攻',
        imgSrc: require('@/assets/oupc/img/member/person11.JPG'),
      },
      {
        name: '島村　真生子',
        txtBody: '',
        job: 'チアリーダー部長・渉内',
        position: '幹部',
        school: '山口県立宇部',
        course: '外国語学部アラビア語専攻',
        imgSrc: require('@/assets/oupc/img/member/person9.JPG'),
      },

      {
        name: '金森　ななみ',
        txtBody: '',
        job: '統制',
        position: '幹部',
        school: '京都府私立大谷',
        course: '外国語学部ロシア語専攻',
        imgSrc: require('@/assets/oupc/img/member/person13.JPG'),
      },
      {
        name: '矢野　乃愛',
        txtBody: '',
        job: '',
        position: '準幹部　',
        school: '兵庫県立神戸',
        course: '経済学部経済経営学科',
        imgSrc: require('@/assets/oupc/img/member/person1.JPG'),
      },
      {
        name: '藤井　尋子',
        txtBody: '',
        job: '',
        position: '準幹部',
        school: '滋賀県立膳所',
        course: '工学部応用理工学科',
        imgSrc: require('@/assets/oupc/img/member/person3.JPG'),
      },
      {
        name: '水田　和',
        txtBody: '',
        job: '',
        position: '二回生',
        school: '兵庫県神戸大学附属中等教育学校',
        course: '法学部国際公共政策学科',
        imgSrc: require('@/assets/oupc/img/member/person6.JPG'),
      },
      {
        name: '宇野　音羽',
        txtBody: '',
        job: '',
        position: '二回生',
        school: '兵庫県立姫路西',
        course: '外国語学部ドイツ語専攻',
        imgSrc: require('@/assets/oupc/img/member/person7.JPG'),
      },
    ],
    members3: [
      {
        name: '伊藤　友貴',
        txtBody: '',
        job: '吹奏部長・財務',
        position: '幹部',
        instrument: 'トランペット',
        school: '愛知県立津島',
        course: '人間科学部人間科学科',

        imgSrc: require('@/assets/oupc/img/member/person14.JPG'),
      },
      {
        name: '向山　晴菜',
        txtBody: '',
        job: '指揮',
        position: '幹部',
        instrument: 'パーカッション',
        subinstrument: 'トロンボーン',
        school: '大阪府私立関西大学高等部',
        course: '法学部国際公共政策学科',
        imgSrc: require('@/assets/oupc/img/member/person4.JPG'),
      },
      {
        name: '清寺　結実子',
        txtBody: '',
        job: '総務',
        position: '幹部',
        instrument: 'トロンボーン',
        school: '愛知県立西春',
        course: '外国語学部日本語専攻',
        imgSrc: require('@/assets/oupc/img/member/person8.JPG'),
      },
      {
        name: '美濃部　和香',
        txtBody: '',
        job: '',
        position: '二回生',
        instrument: 'スーザフォン',
        school: 'Hoffman Estates High School',
        course: '外国語学部フランス語専攻',
        imgSrc: require('@/assets/oupc/img/member/person5.JPG'),
      },
      {
        name: '國府　優香',
        txtBody: '',
        job: '',
        position: '二回生',
        instrument: 'トランペット',
        school: '岡山県立倉敷天城',
        course: '外国語学部アラビア語専攻',
        imgSrc: require('@/assets/oupc/img/member/person15.JPG'),
      },
    ],
  }),
}
